### ISSUE TITLE
Use official TS image

### ISSUE THREAD

**Issue by outime** [outime/ansible-teamspeak3-docker#3]
[The official image](https://hub.docker.com/_/teamspeak) has been around for a while. The current one is rather outdated.

**Comment by outime** [comment]
Done.

**Comment by outime** [comment]
@ogajduse please check if this issue affects you, as you're the only known person that uses this role (besides me and some unknown people). In my experience it went very smooth and no changes should be required from your side.

**Comment by ogajduse** [comment]
@outime Thanks for reaching out to me and apologies for the late reply.
I tested it and it works for me even without changing my playbook. Thanks for this update.
Only one small change is needed, see #4.
